### ISSUE TITLE
Enable login with token_auth only

### ISSUE THREAD

**Issue by jonasjancarik** [matomo-org/matomo-mobile-2#5362]
Our Piwik setup handles user logins through another authorisation system than the default one. An implication of this is that I do not have the username and password necessary to log in using the (Android) mobile app.

Would it maybe be possible to add the option to log in using the [token_auth](http://piwik.org/faq/general/faq_114/) only?

**Comment by tsteur** [comment]
We could do it for sure, but would likely not be happening soon to be honest. There is a rather "dirty" workaround that you could try if you wanted. 

In the file https://github.com/piwik/piwik/blob/2.17.0/plugins/UsersManager/API.php#L791

replace that line with `return 'yourtoken';`.

Then try to log in with any username / password combination. It may work to log in then and save the token on your phone. You would need to immediately replace the original line in that file again and remove `return 'yourtoken';`. Otherwise anyone could get your token and log in.

I haven't tested it but it may work

**Comment by jonasjancarik** [comment]
Thanks for the prompt reply – I don't think I will be able to pull this off in our environment (I don't have that kind of access), but it looks like it could work, so perhaps someone else will find it useful.

In the meantime I will keep my fingers crossed for the token_auth login feature - or for our environment to have the actual Piwik login enabled.

**Comment by tsteur** [comment]
OK thanks for letting us know. I hope we can add https://github.com/piwik/piwik/issues/6559 eventually which will be similar to an auth token so maybe that will help you. I presume we will rather implement that feature sooner than the ability to add token auth. I hope they would let you use that feature.

**Comment by tsteur** [comment]
Hi there, this has finally been fixed in https://github.com/matomo-org/matomo-mobile-2/pull/5407 and https://github.com/matomo-org/matomo-mobile-2/pull/5406 and should be available in the next release (maybe next week). You should then be able to log in using the API token. Ideally I recommend using it together with the upcoming 3.13.6 release.
