### ISSUE TITLE
Statistics loading very slowly when using the app

### ISSUE THREAD

**Issue by chris-ca** [matomo-org/matomo-mobile-2#5451]
For some years I've been using the Android app "Matomo Mobile 2" on my phones to access my self-hosted Matomo instance (VPS) without major issues.

Few days ago I moved to a new place (new ISP, new router) and I've had long delays accessing my Matomo statistics **using the app on Wifi**.

When observing the apache log files of my Matomo instance, the client request does not reach the server until *N* seconds after sending it, whereas *N* corresponds to the *HTTP timeout* setting as defined in the app. The server response is instant.

However the data is retrieved and statistics are displayed instantly on the same devices when:
- accessing the matomo instance **through a mobile browser**
- **using a VPN** (proton)
- **disabling my Wifi** and going through my SIM/mobile data directly

I suspect networking issues to be the root cause of this, but I'm at loss how to debug this, since my unrooted Android 12/13 devices do not allow me to view network traffic (I think).

It appears the app is trying to connect to another endpoint before retrieving data from the actual server. The setting "Anonymous tracking" in the app is disabled.

### Apache log file of affected Matomo instance
```
tail -f /var/log/apache2/access.log 

91.67.xx.xx - - [02/Jul/2023:11:19:26 +0200] "POST /matomo/index.php HTTP/1.1" 200 6162 "-" "Appcelerator Titanium/12.0.0 (moto g72; Android API Level: 31; en-DE;), M
ozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 

```

**Comment by Findus23** [comment]
Just a quick random guess: A delay before the actual request is sent sounds to me as if it would be delayed by the DNS resolution (and maybe your primary DNS server has a timeout?).

**Comment by chris-ca** [comment]
> Just a quick random guess: A delay before the actual request is sent sounds to me as if it would be delayed by the DNS resolution (and maybe your primary DNS server has a timeout?).

Thanks for the idea. I've tried and set the Wifi connection to manual configuration, using Google's DNS, but results are the same. Also, shouldn't the mobile browser have the same issue then?

**Comment by tsteur** [comment]
> It appears the app is trying to connect to another endpoint before retrieving data from the actual server. The setting "Anonymous tracking" in the app is disabled.

@chris-ca is there maybe some redirect happening? Like from HTTP to HTTPS? Although this should be visible in the apache logs as well. The app is otherwise not connecting to any other endpoint. Weird it works when eg using a VPN.

I'm actually currently in a different network as well where I had issues with a very small number of sites as well and enabling VPN made it fast. I didn't investigate further as it isn't my network/router. I haven't looked into it but it does sound like some network configuration issue. Here maybe 2 suggestions to look at:

* MTU Settings: Maximum Transmission Unit (MTU) determines the maximum size of data packets that can be transmitted over the network. If the MTU value is set too high, it can lead to fragmentation and slower speeds. Try lowering the MTU value on your router to see if it improves the performance of the affected sites.
* Firmware Updates: Check if there are any firmware updates available for your router. Outdated firmware can sometimes cause performance issues. Updating to the latest firmware version may resolve certain compatibility issues and improve overall performance.

**Comment by chris-ca** [comment]
> @chris-ca is there maybe some redirect happening? Like from HTTP to HTTPS? Although this should be visible in the apache logs as well. 

I've checked and there's not other request in the Apache log files.

> MTU Settings / Firmware Updates

Does the app use a different TCP stack though than the device browser? Because that's the most inexplicable part for me so far. Unfortunately I don't have control of the router so I cannot modify or check its settings.

**Comment by tsteur** [comment]
> Does the app use a different TCP stack though than the device browser? Because that's the most inexplicable part for me so far. Unfortunately I don't have control of the router so I cannot modify or check its settings.

@chris-ca I'm actually not sure. Does maybe anyone else know?

**Comment by chris-ca** [comment]
Yesterday I updated my backup phone (Android 13/LineageOS) to a new nightly for the first time in maybe 3-4 weeks. The issue has disappeared there (now on 20-20230715-nightly-ocean).
My other phone (Android 12/stock) is still facing issues as described above.
Both devices running Matomo app v2.5.2 so it seems indeed like a bug on OS/networking layer.

**Comment by tsteur** [comment]
Thanks for getting back to us @chris-ca Does this mean we can close this issue assuming it's something to do with the device and less with the app itself?

**Comment by chris-ca** [comment]
Yeah, all things considered this looks more like an OS+networking issue so I don't see what matomo app devs could do here
